# Site settings
title: Orações em Latim
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "latin_prayers.github.io" # the subpath of your site, e.g. /blog/
url: "smedeiros05/latin_prayers.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
